USE [BOOKSHOP]
GO

/****** Object:  Table [dbo].[SACH]    Script Date: 2021-03-26 7:32:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SACH](
	[ID_S] [char](10) NOT NULL,
	[ID_NXB] [nchar](10) NOT NULL,
	[ID_TG] [nchar](10) NOT NULL,
	[ID_TL] [nchar](10) NULL,
	[Ten] [nvarchar](100) NULL,
	[BiaSach] [nchar](50) NULL,
	[Ngay_XuatBan] [date] NULL,
	[KichThuoc] [float] NULL,
	[SoTrang] [int] NULL,
	[TinhTrang] [bit] NULL,
	[SoLuong] [int] NULL,
	[GiaBia] [float] NULL,
	[ChiTiet] [nvarchar](200) NULL,
	[ID_NCC] [nchar](10) NOT NULL,
 CONSTRAINT [PK_SACH] PRIMARY KEY CLUSTERED ([ID_S]))

ALTER TABLE [dbo].[SACH]  WITH CHECK ADD  CONSTRAINT [FK_SACH_NCC] FOREIGN KEY([ID_NXB])
REFERENCES [dbo].[NHA_XUAT_BAN] ([ID_NXB])
GO

ALTER TABLE [dbo].[SACH] CHECK CONSTRAINT [FK_SACH_NCC]
GO

ALTER TABLE [dbo].[SACH]  WITH CHECK ADD  CONSTRAINT [FK_SACH_NCC1] FOREIGN KEY([ID_NCC])
REFERENCES [dbo].[NHA_CUNG_CAP] ([ID_NCC])
GO

ALTER TABLE [dbo].[SACH] CHECK CONSTRAINT [FK_SACH_NCC1]
GO

ALTER TABLE [dbo].[SACH]  WITH CHECK ADD  CONSTRAINT [FK_SACH_TG] FOREIGN KEY([ID_TG])
REFERENCES [dbo].[TAC_GIA] ([ID_TG])
GO

ALTER TABLE [dbo].[SACH] CHECK CONSTRAINT [FK_SACH_TG]
GO

ALTER TABLE [dbo].[SACH]  WITH CHECK ADD  CONSTRAINT [FK_SACH_TL] FOREIGN KEY([ID_TL])
REFERENCES [dbo].[THE_LOAI] ([ID_TL])
GO

ALTER TABLE [dbo].[SACH] CHECK CONSTRAINT [FK_SACH_TL]
GO

