//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homepage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FEEDBACK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FEEDBACK()
        {
            this.ANHFEEDBACKs = new HashSet<ANHFEEDBACK>();
        }
        [Display(Name ="Mã")]
        public int ID_FEEDBACK { get; set; }
        [Display(Name = "Mã sách")]
        public Nullable<int> ID_SACH { get; set; }

        [Display(Name = "Xác nhận mua hàng")]
        public Nullable<bool> XACNHAN_MUAHANG { get; set; }
        [Display(Name = "Điểm đánh giá")]
        public Nullable<byte> DIEM_DANHGIA { get; set; }
        [Display(Name = "Thời gian đăng")]
        public string THOIGIAN_DANG { get; set; }
        [Display(Name = "Nội dung")]
        public string NOIDUNG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANHFEEDBACK> ANHFEEDBACKs { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
